spring:
  data:
    redis:
      host: livk.com
      password: 123456
      port: 6379
  redisson:
    config:
      singleServerConfig:
        address: "redis://livk.com:6379"
        database: 7
        idleConnectionTimeout: 10000
        connectTimeout: 10000
        timeout: 3000
        retryAttempts: 3
        subscriptionsPerConnection: 5
        subscriptionConnectionMinimumIdleSize: 1
        subscriptionConnectionPoolSize: 50
        connectionMinimumIdleSize: 32
        connectionPoolSize: 64
        dnsMonitoringInterval: 5000
      threads: 0
      nettyThreads: 0
      codec: '!org.redisson.codec.JsonJackson3Codec { }'
      transportMode: "NIO"
      password: "123456"
